"""empty message

Revision ID: 116b661e7b93
Revises: 8da1e8acc104
Create Date: 2024-10-15 19:29:37.266529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116b661e7b93'
down_revision: Union[str, None] = '8da1e8acc104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('degree', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_results', 'degree')
    # ### end Alembic commands ###
