"""empty message

Revision ID: 5fb7ae814046
Revises: 029d9a77a5e9
Create Date: 2024-10-06 11:57:43.777946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb7ae814046'
down_revision: Union[str, None] = '029d9a77a5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('first_test', sa.Integer(), nullable=True))
    op.add_column('test_results', sa.Column('second_test', sa.Integer(), nullable=True))
    op.add_column('test_results', sa.Column('third_test', sa.Integer(), nullable=True))
    op.add_column('test_results', sa.Column('fourth_test', sa.Integer(), nullable=True))
    op.add_column('test_results', sa.Column('gestures_result', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_results', 'gestures_result')
    op.drop_column('test_results', 'fourth_test')
    op.drop_column('test_results', 'third_test')
    op.drop_column('test_results', 'second_test')
    op.drop_column('test_results', 'first_test')
    # ### end Alembic commands ###
