"""empty message

Revision ID: 8da1e8acc104
Revises: 5fb7ae814046
Create Date: 2024-10-08 20:13:10.742804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da1e8acc104'
down_revision: Union[str, None] = '5fb7ae814046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('diagnosis', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_results', 'diagnosis')
    # ### end Alembic commands ###
