"""empty message

Revision ID: 9ce8dcc6ad7e
Revises: 
Create Date: 2024-10-05 20:44:21.850215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce8dcc6ad7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('test_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=True),
    sa.Column('patient_birth_date', sa.DateTime(), nullable=True),
    sa.Column('patient_phone_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('complaints', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('recommendation_for_user', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('recommendation_for_doctor', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('am', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('av', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sp', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('nfr_points', sa.Integer(), nullable=True),
    sa.Column('kfr_points', sa.Integer(), nullable=True),
    sa.Column('symptoms_points', sa.Integer(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_results')
    op.drop_table('users')
    # ### end Alembic commands ###
